### PR TITLE
Chemical improvements

### LINKED ISSUE #509: Chemicals: corrosive reaction breaks blocks partially
See if it is possible to make corrosive reactions break blocks partially instead of breaking them instantly.

### LINKED ISSUE #710: [Bug] Chemicals: explosion, fire ,... don't respect rules
**Describe the bug**
Chemical effects don't respect gamrules like `mobGriefing` or `doFireTick`

**To Reproduce**
Just use them ?

**Expected behavior**
See Creepers and or Explosions.

### PR DESCRIPTION
**Pull request by RobbeNooyens**
- resolves #710
- resolves #509

### CODE REVIEW

File: src/main/java/be/minelabs/entity/CorrosiveEntity.java [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+    // On every tick, set the blockbreakinginfo of the block at the blockpos to 5
+    @Override
+    public void tick() {
+        super.tick();
+        // If the block at the blockpos has turned into air, remove the entity
+        if (this.blockPos != null && this.world.getBlockState(blockPos).isOf(net.minecraft.block.Blocks.AIR)) {
+            this.world.setBlockBreakingInfo(this.getId(), this.blockPos, 0);
+            this.remove(RemovalReason.DISCARDED);
+        }
+        if (this.blockPos != null) {
```
Comment (JoeyDP) [inline src/main/java/be/minelabs/entity/CorrosiveEntity.java:41]: I think you only want the tick function to run on the server. This check is used as a proxy because the value is probably not set on the client. Could you test this and make it more clear by checking for server world instead.

File: src/main/java/be/minelabs/entity/CorrosiveEntity.java [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+    }
+
+    @Override
+    protected void initDataTracker() {
+        // TODO Auto-generated method stub
+    }
+
+    @Override
+    protected void readCustomDataFromNbt(NbtCompound nbt) {
+        // TODO Auto-generated method stub
```
Comment (JoeyDP) [inline src/main/java/be/minelabs/entity/CorrosiveEntity.java:65]: Implement

File: src/main/java/be/minelabs/entity/CorrosiveEntity.java [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+    }
+
+    @Override
+    protected void writeCustomDataToNbt(NbtCompound nbt) {
+        // TODO Auto-generated method stub
```
Comment (JoeyDP) [inline src/main/java/be/minelabs/entity/CorrosiveEntity.java:70]: Implement

File: src/main/java/be/minelabs/entity/CorrosiveEntity.java [hunk 4]
```diff
@@ -0,0 +1,72 @@
...
+            if (progress == 10) {
+                this.remove(RemovalReason.DISCARDED);
+                this.world.setBlockBreakingInfo(this.getId(), this.blockPos, 0);
+                this.world.breakBlock(this.blockPos, this.world.getGameRules().getBoolean(GameRules.DO_TILE_DROPS));
+            } else {
+                this.world.setBlockBreakingInfo(this.getId(), this.blockPos, progress);
+            }
+        }
+    }
+
```
Comment (JoeyDP) [inline src/main/java/be/minelabs/entity/CorrosiveEntity.java:57]: What happens when this entity is killed or otherwise disappears before the block is broken? Do we need an 'onDeath' callback (I don't recall the name) to reset block break progress?

Comment (JoeyDP) [inline src/main/java/be/minelabs/entity/CorrosiveEntity.java:57]: Does it handle the case when a player mines a block at the same time? As long as it doesn't crash it is fine. Some weird behavior like breaking another block when the player mines and quickly replaces is acceptable.

**Review by JoeyDP — CHANGES_REQUESTED** [review]

File: src/main/java/be/minelabs/entity/CorrosiveEntity.java (hunk 1 above)
Comment (pixar02) [reply src/main/java/be/minelabs/entity/CorrosiveEntity.java:41]: When looking into the method `setBlockBreakingInfo()`
The Server world only has it defined as an abstract method.
And Client actually does something with it.

So if anything we could check for client and only tick on client. But since server doesn't handle it don't see the issue.

File: src/main/java/be/minelabs/entity/CorrosiveEntity.java (hunk 4 above)
Comment (pixar02) [reply src/main/java/be/minelabs/entity/CorrosiveEntity.java:57]: Doesn't crash. There is no actual data that gets writting just the breaking effect is rendered.

Comment (pixar02) [reply src/main/java/be/minelabs/entity/CorrosiveEntity.java:58]: Minecraft rendering (World Renderer) cleans them if needed. 
image

File: src/main/java/be/minelabs/entity/CorrosiveEntity.java (hunk 1 above)
Comment (JoeyDP) [reply src/main/java/be/minelabs/entity/CorrosiveEntity.java:42]: Did you check `ServerWorld` too? It seems like something the server should coordinate. For example when one player mines something, don't other players see the progress as well?

Whether we need the server to coordinate this is up for debate. As long as all clients have the entities as well, I guess it will also render just fine, as long as the actual block breaking logic remains server side.

Comment (pixar02) [reply src/main/java/be/minelabs/entity/CorrosiveEntity.java:42]: `ServerWorld` only triggers the networking.
```java
public void setBlockBreakingInfo(int entityId, BlockPos pos, int progress) {
        for (ServerPlayerEntity serverPlayerEntity : this.server.getPlayerManager().getPlayerList()) {
            double f;
            double e;
            double d;
            if (serverPlayerEntity == null || serverPlayerEntity.world != this || serverPlayerEntity.getId() == entityId || !((d = (double)pos.getX() - serverPlayerEntity.getX()) * d + (e = (double)pos.getY() - serverPlayerEntity.getY()) * e + (f = (double)pos.getZ() - serverPlayerEntity.getZ()) * f < 1024.0)) continue;
            serverPlayerEntity.networkHandler.sendPacket(new BlockBreakingProgressS2CPacket(entityId, pos, progress));
        }
    } 
````
   
But `ClientWorld` effects the visual.
```java
public void setBlockBreakingInfo(int entityId, BlockPos pos, int progress) {
        this.worldRenderer.setBlockBreakingInfo(entityId, pos, progress);
    }
```
