### PR TITLE
Point charge

### LINKED ISSUE #479: Point charge does not drop when broken
When breaking the point charge with a pickaxe, it does not drop.
The contents of the pointcharge do drop

### PR DESCRIPTION
**Pull request by BertJorissen**
- scaling of arrows
- loot table
- 
closes #479 #503

### CODE REVIEW

File: src/main/java/be/uantwerpen/minelabs/block/entity/ChargedPointBlockEntity.java [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+import net.minecraft.util.collection.DefaultedList;
+import net.minecraft.util.math.BlockPos;
+import net.minecraft.util.math.Direction;
+import org.jetbrains.annotations.Nullable;
+
+import java.util.ArrayList;
+
+public class ChargedPointBlockEntity extends ChargedBlockEntity implements ImplementedInventory, NamedScreenHandlerFactory {
+
+    private final DefaultedList<ItemStack> INVENTORY = DefaultedList.ofSize(1, ItemStack.EMPTY);
```
Comment (JoeyDP) [inline src/main/java/be/uantwerpen/minelabs/block/entity/ChargedPointBlockEntity.java:26]: All caps is used for static fields. Change to lower case.

File: src/main/java/be/uantwerpen/minelabs/block/entity/ChargedPointBlockEntity.java [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+
+    @Nullable
+    @Override
+    public ScreenHandler createMenu(int syncId, PlayerInventory inv, PlayerEntity player) {
+        return new ChargedPointBlockScreenHandler(syncId, inv, this);
+    }
+
+    public void setInventory(ItemStack inventoryIn) {
+        INVENTORY.set(0, inventoryIn);
+        inventoryChanged();
```
Comment (JoeyDP) [inline src/main/java/be/uantwerpen/minelabs/block/entity/ChargedPointBlockEntity.java:79]: If you use SimpleInventory instead of extending from ImplementedInventory, you can add a listener to the inventory. This makes sure the update is also called when for example the ScreenHandler edits the contents.

File: src/main/java/be/uantwerpen/minelabs/gui/charged_point_gui/ChargedPointBlockScreenHandler.java [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+        this(syncId, inventory, new SimpleInventory(1));
+    }
+
+    public ChargedPointBlockScreenHandler(int syncId, @NotNull PlayerInventory playerInventory, Inventory inventory) {
+        super(ScreenHandlers.CHARGED_POINT_SCREEN_HANDLER, syncId);
+        checkSize(inventory, 1);
+        this.inventory = inventory;
+        inventory.onOpen(playerInventory.player);
+
+        //TODO CORRECT COORDS SLOT
```
Comment (JoeyDP) [inline src/main/java/be/uantwerpen/minelabs/gui/charged_point_gui/ChargedPointBlockScreenHandler.java:29]: Are they correct now? Remove comment then.

**Review by JoeyDP — CHANGES_REQUESTED** [review]
See comments in changes. Haven't tested in game but looked stable enough to merge during demo.

File: src/main/java/be/uantwerpen/minelabs/gui/charged_point_gui/ChargedPointBlockScreenHandler.java (hunk 3 above)
Comment (pixar02) [reply src/main/java/be/uantwerpen/minelabs/gui/charged_point_gui/ChargedPointBlockScreenHandler.java:29]: Incase Art decided on a different position for the item.

File: src/main/java/be/uantwerpen/minelabs/block/entity/ChargedPointBlockEntity.java (hunk 2 above)
Comment (pixar02) [reply src/main/java/be/uantwerpen/minelabs/block/entity/ChargedPointBlockEntity.java:79]: The method is being used when the animation has ended and the point-charged is placed again (as an actual block, with entity).
Screenhandler already calls the onClose method of the inventory. 
Which in turn updates the field.

File: src/main/java/be/uantwerpen/minelabs/block/entity/ChargedPointBlockEntity.java (hunk 1 above)
Comment (JoeyDP) [reply src/main/java/be/uantwerpen/minelabs/block/entity/ChargedPointBlockEntity.java:26]: final doesn't indicate const any more than static does. Instance variables are camel case, even when final which just means they can be assigned only once. Things  we want to serve as constants use all caps to indicate this. In this case I really don't think you want the inventory to be a constant.

File: src/main/java/be/uantwerpen/minelabs/block/entity/ChargedPointBlockEntity.java (hunk 2 above)
Comment (BertJorissen) [reply src/main/java/be/uantwerpen/minelabs/block/entity/ChargedPointBlockEntity.java:79]: Do we need to update this?

Comment (JoeyDP) [reply src/main/java/be/uantwerpen/minelabs/block/entity/ChargedPointBlockEntity.java:79]: No it's fine by me as long as it works. Ready for merge!
